# Configuration
site_name: Travel
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - content.action.edit
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 80%
      height: auto
      zoomable: false
      draggable: false
      auto_caption: false
      caption_position: bottom

# Repository
repo_name: Evilrabbit520/Travel
repo_url: https://github.com/Evilrabbit520/Travel
edit_uri: tree/main/docs
version: 1.0.0

extra:
  top_menu:
    - label: Home
      href: /
    - label: About Us
      href: /about
    - label: Contact
      href: /contact
  alternate:
    - name: 中文
      link: /
      lang: zh
    # - name: English
    #   link: /en/
    #   lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Evilrabbit520/Travel
  generator: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - tables
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Copyright
copyright: Copyright &copy; 2024 Wang Yujia

# Page tree
nav:
- 首页: /index.html
- 旅行攻略:
  - 甘肃省 &nbsp; Gansu:
    # [icon: material/book-open-outline]
    - Gansu/index.md
    - 1 &nbsp; 市州景点: Gansu/CityAndStateAttractions/index.md
    - 2 &nbsp; 景点攻略: Gansu/howToUse.md
    - 3 &nbsp; 路线攻略: Gansu/summary.md
# - 参与编写: /index.html
# - 关于项目: /index.html